SET NOCOUNT ON;
SET XACT_ABORT ON;

USE [QLHV_APP];
IF DB_NAME()<>N'QLHV_APP' OR DATABASE_PRINCIPAL_ID(N'QLHV_RealtimeWorkerRole') IS NULL
    THROW 532730,'TVP_TARGET_WORKER_ROLE_MISSING',1;
GRANT SELECT,INSERT,UPDATE ON dbo.App_KhoaHoc_XeTap TO QLHV_RealtimeWorkerRole;
GRANT SELECT,INSERT,UPDATE ON dbo.App_TeacherVehicleProjectionCheckpoint TO QLHV_RealtimeWorkerRole;
GRANT SELECT,INSERT ON dbo.App_TeacherVehicleProjectionCycle TO QLHV_RealtimeWorkerRole;
DENY DELETE ON dbo.App_TeacherVehicleProjectionCheckpoint TO QLHV_RealtimeWorkerRole;
DENY DELETE,UPDATE ON dbo.App_TeacherVehicleProjectionCycle TO QLHV_RealtimeWorkerRole;
DENY INSERT,UPDATE,DELETE ON dbo.App_GiaoVien TO [NT SERVICE\QLHV_APP_Api];
DENY INSERT,UPDATE,DELETE ON dbo.App_XeTap TO [NT SERVICE\QLHV_APP_Api];
DENY INSERT,UPDATE,DELETE ON dbo.App_KhoaHoc_GiaoVien TO [NT SERVICE\QLHV_APP_Api];
DENY INSERT,UPDATE,DELETE ON dbo.App_KhoaHoc_XeTap TO [NT SERVICE\QLHV_APP_Api];

USE [CSDL_OTO];
IF DATABASE_PRINCIPAL_ID(N'QLHV_RealtimeWorkerRole') IS NULL
    THROW 532731,'TVP_OTO_WORKER_ROLE_MISSING',1;
GRANT SELECT,VIEW CHANGE TRACKING ON dbo.GiaoVien TO QLHV_RealtimeWorkerRole;
GRANT SELECT,VIEW CHANGE TRACKING ON dbo.XeTap TO QLHV_RealtimeWorkerRole;
GRANT SELECT,VIEW CHANGE TRACKING ON dbo.KhoaHoc_GiaoVien TO QLHV_RealtimeWorkerRole;
GRANT SELECT,VIEW CHANGE TRACKING ON dbo.KhoaHoc_XeTap TO QLHV_RealtimeWorkerRole;
DENY INSERT,UPDATE,DELETE ON dbo.GiaoVien TO QLHV_RealtimeWorkerRole;
DENY INSERT,UPDATE,DELETE ON dbo.XeTap TO QLHV_RealtimeWorkerRole;
DENY INSERT,UPDATE,DELETE ON dbo.KhoaHoc_GiaoVien TO QLHV_RealtimeWorkerRole;
DENY INSERT,UPDATE,DELETE ON dbo.KhoaHoc_XeTap TO QLHV_RealtimeWorkerRole;

USE [CSDL_MOTO];
IF DATABASE_PRINCIPAL_ID(N'QLHV_RealtimeWorkerRole') IS NULL
    THROW 532732,'TVP_MOTO_WORKER_ROLE_MISSING',1;
GRANT SELECT,VIEW CHANGE TRACKING ON dbo.GiaoVien TO QLHV_RealtimeWorkerRole;
GRANT SELECT,VIEW CHANGE TRACKING ON dbo.XeTap TO QLHV_RealtimeWorkerRole;
GRANT SELECT,VIEW CHANGE TRACKING ON dbo.KhoaHoc_GiaoVien TO QLHV_RealtimeWorkerRole;
GRANT SELECT,VIEW CHANGE TRACKING ON dbo.KhoaHoc_XeTap TO QLHV_RealtimeWorkerRole;
DENY INSERT,UPDATE,DELETE ON dbo.GiaoVien TO QLHV_RealtimeWorkerRole;
DENY INSERT,UPDATE,DELETE ON dbo.XeTap TO QLHV_RealtimeWorkerRole;
DENY INSERT,UPDATE,DELETE ON dbo.KhoaHoc_GiaoVien TO QLHV_RealtimeWorkerRole;
DENY INSERT,UPDATE,DELETE ON dbo.KhoaHoc_XeTap TO QLHV_RealtimeWorkerRole;

USE [QLHV_APP];
EXECUTE AS USER=N'NT SERVICE\QLHV_APP_RealtimeWorker';
IF HAS_PERMS_BY_NAME(N'dbo.App_TeacherVehicleProjectionCheckpoint',N'OBJECT',N'UPDATE')<>1 OR
   HAS_PERMS_BY_NAME(N'dbo.App_TeacherVehicleProjectionCycle',N'OBJECT',N'INSERT')<>1 OR
   HAS_PERMS_BY_NAME(N'dbo.App_TeacherVehicleProjectionCycle',N'OBJECT',N'DELETE')<>0
    THROW 532733,'TVP_TARGET_PERMISSION_VERIFY_FAILED',1;
REVERT;
SELECT N'TEACHER_VEHICLE_PROJECTION_PERMISSION_PASS' Marker;
