USE [QLHV_APP];
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;
GO

IF DB_NAME()<>N'QLHV_APP'
    THROW 528550, 'RT03_RECOVERY_ROLLBACK_DATABASE_REJECTED', 1;

IF OBJECT_ID(N'dbo.App_Rt03FullConvergenceSession',N'U') IS NOT NULL
   AND EXISTS(SELECT 1 FROM dbo.App_Rt03FullConvergenceSession)
    THROW 528551, 'RT03_RECOVERY_ROLLBACK_REFUSED_NONEMPTY_SESSION', 1;
IF OBJECT_ID(N'dbo.App_Rt03FullConvergenceDomain',N'U') IS NOT NULL
   AND EXISTS(SELECT 1 FROM dbo.App_Rt03FullConvergenceDomain)
    THROW 528552, 'RT03_RECOVERY_ROLLBACK_REFUSED_NONEMPTY_DOMAIN', 1;
IF OBJECT_ID(N'dbo.App_Rt03FullConvergenceMarker',N'U') IS NOT NULL
   AND EXISTS(SELECT 1 FROM dbo.App_Rt03FullConvergenceMarker)
    THROW 528553, 'RT03_RECOVERY_ROLLBACK_REFUSED_NONEMPTY_MARKER', 1;
GO

DROP PROCEDURE IF EXISTS dbo.usp_App_Rt03FinalizeFullConvergence;
DROP PROCEDURE IF EXISTS dbo.usp_App_Rt03VerifyFullConvergence;
DROP PROCEDURE IF EXISTS dbo.usp_App_Rt03RecordFullConvergenceDomain;
DROP PROCEDURE IF EXISTS dbo.usp_App_Rt03BeginFullConvergence;
GO

DROP TABLE IF EXISTS dbo.App_Rt03FullConvergenceMarker;
DROP TABLE IF EXISTS dbo.App_Rt03FullConvergenceDomain;
DROP TABLE IF EXISTS dbo.App_Rt03FullConvergenceSession;
GO

SELECT N'RT03_V5_FULL_CONVERGENCE_SCHEMA_ROLLED_BACK' AS Result;
GO
