USE [$(Rt03TargetDatabase)];
GO
SET NOCOUNT ON;
SET XACT_ABORT ON;

IF DB_NAME()<>N'QLHV_APP'
   AND ISNULL(TRY_CONVERT(bit,SESSION_CONTEXT(N'RT03_MASTER_DISPOSABLE_REHEARSAL')),0)<>1
    THROW 527842, 'RT03_MASTER_PERMISSION_ROLLBACK_WRONG_DATABASE', 1;

IF OBJECT_ID(N'dbo.App_Rt03RealtimeControl',N'U') IS NOT NULL
   AND EXISTS(SELECT 1 FROM dbo.App_Rt03RealtimeControl WHERE State<>N'OFF')
    THROW 527840, 'RT03_MASTER_PERMISSION_ROLLBACK_REQUIRES_OFF', 1;
IF OBJECT_ID(N'dbo.App_Rt03RealtimeRunRequest',N'U') IS NOT NULL
   AND EXISTS(SELECT 1 FROM dbo.App_Rt03RealtimeRunRequest WHERE ActiveSlot=1)
    THROW 527841, 'RT03_MASTER_PERMISSION_ROLLBACK_RUN_ACTIVE', 1;

IF USER_ID(N'QLHV_RealtimeWorkerRole') IS NOT NULL
BEGIN
    REVOKE SELECT,UPDATE,DELETE ON OBJECT::dbo.App_Rt03RealtimeControl
        FROM [QLHV_RealtimeWorkerRole];
    REVOKE INSERT,UPDATE,DELETE ON OBJECT::dbo.App_Rt03RealtimeControlAudit
        FROM [QLHV_RealtimeWorkerRole];
    REVOKE SELECT,INSERT,UPDATE,DELETE ON OBJECT::dbo.App_Rt03RealtimeRunRequest
        FROM [QLHV_RealtimeWorkerRole];
END;
SELECT N'PASS' AS PermissionRollbackStatus;
GO
