USE [CSDL_OTO];
GO

/*
  READ-ONLY: aggregate teacher data-quality report.
  No name, identity document, address, phone number or photo path is returned.
*/

SELECT N'TOTAL' AS Metric, CONVERT(nvarchar(40), COUNT_BIG(*)) AS MetricValue FROM dbo.GiaoVien
UNION ALL SELECT N'ACTIVE', CONVERT(nvarchar(40), SUM(CASE WHEN TrangThai = 1 THEN 1 ELSE 0 END)) FROM dbo.GiaoVien
UNION ALL SELECT N'INACTIVE_OR_STOPPED', CONVERT(nvarchar(40), SUM(CASE WHEN TrangThai = 0 THEN 1 ELSE 0 END)) FROM dbo.GiaoVien
UNION ALL SELECT N'PENDING_NOT_REPRESENTABLE', N'N/A'
UNION ALL SELECT N'LOCKED_NOT_REPRESENTABLE', N'N/A'
UNION ALL SELECT N'SOFT_DELETED_NOT_REPRESENTABLE', N'N/A'
UNION ALL SELECT N'MISSING_TEACHER_CODE', CONVERT(nvarchar(40), SUM(CASE WHEN NULLIF(LTRIM(RTRIM(MaGV)), N'') IS NULL THEN 1 ELSE 0 END)) FROM dbo.GiaoVien
UNION ALL SELECT N'MISSING_GPLX_CLASS', CONVERT(nvarchar(40), SUM(CASE WHEN NULLIF(LTRIM(RTRIM(HangGPLX)), N'') IS NULL THEN 1 ELSE 0 END)) FROM dbo.GiaoVien
UNION ALL SELECT N'MISSING_CERTIFICATE_NUMBER', CONVERT(nvarchar(40), SUM(CASE WHEN NULLIF(LTRIM(RTRIM(SoQD_GCN)), N'') IS NULL THEN 1 ELSE 0 END)) FROM dbo.GiaoVien
UNION ALL SELECT N'MISSING_CERTIFICATE_DATE', CONVERT(nvarchar(40), SUM(CASE WHEN NgayQD_GCN IS NULL THEN 1 ELSE 0 END)) FROM dbo.GiaoVien
UNION ALL SELECT N'MISSING_TEACHABLE_CLASS', CONVERT(nvarchar(40), SUM(CASE WHEN NULLIF(LTRIM(RTRIM(CacHangGPLXDuocDT)), N'') IS NULL THEN 1 ELSE 0 END)) FROM dbo.GiaoVien
UNION ALL SELECT N'MISSING_ORGANIZATION', CONVERT(nvarchar(40), SUM(CASE WHEN NULLIF(LTRIM(RTRIM(MaCSDT)), N'') IS NULL THEN 1 ELSE 0 END)) FROM dbo.GiaoVien
UNION ALL SELECT N'MISSING_PHOTO_PATH', CONVERT(nvarchar(40), SUM(CASE WHEN NULLIF(LTRIM(RTRIM(AnhCD)), N'') IS NULL THEN 1 ELSE 0 END)) FROM dbo.GiaoVien
UNION ALL SELECT N'MISSING_GPLX_EXPIRY', CONVERT(nvarchar(40), SUM(CASE WHEN NgayHHGPLX IS NULL THEN 1 ELSE 0 END)) FROM dbo.GiaoVien
UNION ALL SELECT N'EXPIRED_GPLX', CONVERT(nvarchar(40), SUM(CASE WHEN NgayHHGPLX < CONVERT(date, GETDATE()) THEN 1 ELSE 0 END)) FROM dbo.GiaoVien
UNION ALL SELECT N'DOB_NOT_VALID_YYYYMMDD', CONVERT(nvarchar(40), SUM(CASE WHEN TRY_CONVERT(date, NgaySinh, 112) IS NULL THEN 1 ELSE 0 END)) FROM dbo.GiaoVien
UNION ALL SELECT N'DOB_VALID_DDMMYYYY', CONVERT(nvarchar(40), SUM(CASE WHEN TRY_CONVERT(date, RIGHT(NgaySinh, 4) + SUBSTRING(NgaySinh, 3, 2) + LEFT(NgaySinh, 2), 112) IS NOT NULL THEN 1 ELSE 0 END)) FROM dbo.GiaoVien
UNION ALL SELECT N'MIN_CREATED_AT', CONVERT(nvarchar(40), MIN(NgayTao), 126) FROM dbo.GiaoVien
UNION ALL SELECT N'MAX_CREATED_AT', CONVERT(nvarchar(40), MAX(NgayTao), 126) FROM dbo.GiaoVien
UNION ALL SELECT N'MAX_UPDATED_AT', CONVERT(nvarchar(40), MAX(NgaySua), 126) FROM dbo.GiaoVien;

SELECT N'DUPLICATE_IDENTITY_DOCUMENT_GROUPS' AS Metric, COUNT_BIG(*) AS MetricValue
FROM
(
    SELECT REPLACE(REPLACE(UPPER(LTRIM(RTRIM(SoCMT))), N' ', N''), N'-', N'') AS NormalizedKey
    FROM dbo.GiaoVien
    WHERE NULLIF(LTRIM(RTRIM(SoCMT)), N'') IS NOT NULL
    GROUP BY REPLACE(REPLACE(UPPER(LTRIM(RTRIM(SoCMT))), N' ', N''), N'-', N'')
    HAVING COUNT_BIG(*) > 1
) AS duplicateGroup
UNION ALL
SELECT N'DUPLICATE_NAME_AND_DOB_REVIEW_GROUPS', COUNT_BIG(*)
FROM
(
    SELECT
        UPPER(LTRIM(RTRIM(HoTenDem)) + N' ' + LTRIM(RTRIM(TenGV))) AS NormalizedName,
        NgaySinh
    FROM dbo.GiaoVien
    GROUP BY UPPER(LTRIM(RTRIM(HoTenDem)) + N' ' + LTRIM(RTRIM(TenGV))), NgaySinh
    HAVING COUNT_BIG(*) > 1
) AS duplicateGroup;

SELECT
    CONVERT(char(7), NgayTao, 120) AS CreatedMonth,
    COUNT_BIG(*) AS TeacherRows
FROM dbo.GiaoVien
GROUP BY CONVERT(char(7), NgayTao, 120)
ORDER BY CreatedMonth;

SELECT
    CASE
        WHEN NULLIF(LTRIM(RTRIM(AnhCD)), N'') IS NULL THEN N'MISSING'
        WHEN CHARINDEX(N':', AnhCD) > 0 OR LEFT(LTRIM(AnhCD), 1) IN (N'/', N'\') THEN N'ROOTED_OR_ABSOLUTE'
        WHEN AnhCD LIKE N'%..%' THEN N'PARENT_SEGMENT_RISK'
        ELSE N'RELATIVE_CANDIDATE'
    END AS PhotoPathClass,
    COUNT_BIG(*) AS TeacherRows
FROM dbo.GiaoVien
GROUP BY
    CASE
        WHEN NULLIF(LTRIM(RTRIM(AnhCD)), N'') IS NULL THEN N'MISSING'
        WHEN CHARINDEX(N':', AnhCD) > 0 OR LEFT(LTRIM(AnhCD), 1) IN (N'/', N'\') THEN N'ROOTED_OR_ABSOLUTE'
        WHEN AnhCD LIKE N'%..%' THEN N'PARENT_SEGMENT_RISK'
        ELSE N'RELATIVE_CANDIDATE'
    END;

SELECT @@TRANCOUNT AS SessionOpenTransactionCount;
GO
