USE [CSDL_OTO];
GO

/*
  READ-ONLY: aggregate vehicle data-quality report.
  No plate, registration, chassis or engine value is returned.
*/

SELECT N'TOTAL' AS Metric, CONVERT(nvarchar(40), COUNT_BIG(*)) AS MetricValue FROM dbo.XeTap
UNION ALL SELECT N'ACTIVE', CONVERT(nvarchar(40), SUM(CASE WHEN TrangThai = 1 THEN 1 ELSE 0 END)) FROM dbo.XeTap
UNION ALL SELECT N'INACTIVE', CONVERT(nvarchar(40), SUM(CASE WHEN TrangThai = 0 THEN 1 ELSE 0 END)) FROM dbo.XeTap
UNION ALL SELECT N'LIQUIDATED_NOT_REPRESENTABLE', N'N/A'
UNION ALL SELECT N'PENDING_NOT_REPRESENTABLE', N'N/A'
UNION ALL SELECT N'SOFT_DELETED_NOT_REPRESENTABLE', N'N/A'
UNION ALL SELECT N'MISSING_PLATE', CONVERT(nvarchar(40), SUM(CASE WHEN NULLIF(LTRIM(RTRIM(BienSoXe)), N'') IS NULL THEN 1 ELSE 0 END)) FROM dbo.XeTap
UNION ALL SELECT N'MISSING_FRAME_NUMBER', CONVERT(nvarchar(40), SUM(CASE WHEN NULLIF(LTRIM(RTRIM(SoKhung)), N'') IS NULL THEN 1 ELSE 0 END)) FROM dbo.XeTap
UNION ALL SELECT N'MISSING_ENGINE_NUMBER', CONVERT(nvarchar(40), SUM(CASE WHEN NULLIF(LTRIM(RTRIM(SoDongCo)), N'') IS NULL THEN 1 ELSE 0 END)) FROM dbo.XeTap
UNION ALL SELECT N'MISSING_REGISTRATION', CONVERT(nvarchar(40), SUM(CASE WHEN NULLIF(LTRIM(RTRIM(SoDK)), N'') IS NULL THEN 1 ELSE 0 END)) FROM dbo.XeTap
UNION ALL SELECT N'MISSING_VEHICLE_CLASS', CONVERT(nvarchar(40), SUM(CASE WHEN NULLIF(LTRIM(RTRIM(HangGPLXXe)), N'') IS NULL THEN 1 ELSE 0 END)) FROM dbo.XeTap
UNION ALL SELECT N'MISSING_BRAND', CONVERT(nvarchar(40), SUM(CASE WHEN NULLIF(LTRIM(RTRIM(COALESCE(NhanHieu, HangXe))), N'') IS NULL THEN 1 ELSE 0 END)) FROM dbo.XeTap
UNION ALL SELECT N'MISSING_PHOTO_PATH', CONVERT(nvarchar(40), SUM(CASE WHEN NULLIF(LTRIM(RTRIM(DuongDanAnh)), N'') IS NULL THEN 1 ELSE 0 END)) FROM dbo.XeTap
UNION ALL SELECT N'EXPIRED_TRAINING_PERMIT', CONVERT(nvarchar(40), SUM(CASE WHEN NgayHHGPXTL < CONVERT(date, GETDATE()) THEN 1 ELSE 0 END)) FROM dbo.XeTap
UNION ALL SELECT N'EXPIRED_INSPECTION', CONVERT(nvarchar(40), SUM(CASE WHEN NgayHHGCNKD < CONVERT(date, GETDATE()) THEN 1 ELSE 0 END)) FROM dbo.XeTap
UNION ALL SELECT N'INSURANCE_NOT_EFFECTIVE', CONVERT(nvarchar(40), SUM(CASE WHEN BaoHiem = 0 THEN 1 ELSE 0 END)) FROM dbo.XeTap
UNION ALL SELECT N'MIN_CREATED_AT', CONVERT(nvarchar(40), MIN(NgayTao), 126) FROM dbo.XeTap
UNION ALL SELECT N'MAX_CREATED_AT', CONVERT(nvarchar(40), MAX(NgayTao), 126) FROM dbo.XeTap
UNION ALL SELECT N'MAX_UPDATED_AT', CONVERT(nvarchar(40), MAX(NgaySua), 126) FROM dbo.XeTap;

SELECT N'DUPLICATE_NORMALIZED_PLATE_GROUPS' AS Metric, COUNT_BIG(*) AS MetricValue
FROM
(
    SELECT REPLACE(REPLACE(REPLACE(UPPER(LTRIM(RTRIM(BienSoXe))), N' ', N''), N'-', N''), N'.', N'') AS NormalizedKey
    FROM dbo.XeTap
    GROUP BY REPLACE(REPLACE(REPLACE(UPPER(LTRIM(RTRIM(BienSoXe))), N' ', N''), N'-', N''), N'.', N'')
    HAVING COUNT_BIG(*) > 1
) AS duplicateGroup
UNION ALL
SELECT N'DUPLICATE_REGISTRATION_GROUPS', COUNT_BIG(*)
FROM
(
    SELECT UPPER(LTRIM(RTRIM(SoDK))) AS NormalizedKey
    FROM dbo.XeTap
    WHERE NULLIF(LTRIM(RTRIM(SoDK)), N'') IS NOT NULL
    GROUP BY UPPER(LTRIM(RTRIM(SoDK)))
    HAVING COUNT_BIG(*) > 1
) AS duplicateGroup
UNION ALL
SELECT N'DUPLICATE_FRAME_NUMBER_GROUPS', COUNT_BIG(*)
FROM
(
    SELECT UPPER(LTRIM(RTRIM(SoKhung))) AS NormalizedKey
    FROM dbo.XeTap
    WHERE NULLIF(LTRIM(RTRIM(SoKhung)), N'') IS NOT NULL
    GROUP BY UPPER(LTRIM(RTRIM(SoKhung)))
    HAVING COUNT_BIG(*) > 1
) AS duplicateGroup
UNION ALL
SELECT N'DUPLICATE_ENGINE_NUMBER_GROUPS', COUNT_BIG(*)
FROM
(
    SELECT UPPER(LTRIM(RTRIM(SoDongCo))) AS NormalizedKey
    FROM dbo.XeTap
    WHERE NULLIF(LTRIM(RTRIM(SoDongCo)), N'') IS NOT NULL
    GROUP BY UPPER(LTRIM(RTRIM(SoDongCo)))
    HAVING COUNT_BIG(*) > 1
) AS duplicateGroup;

SELECT
    CONVERT(char(7), NgayTao, 120) AS CreatedMonth,
    COUNT_BIG(*) AS VehicleRows
FROM dbo.XeTap
GROUP BY CONVERT(char(7), NgayTao, 120)
ORDER BY CreatedMonth;

SELECT
    CASE
        WHEN NULLIF(LTRIM(RTRIM(DuongDanAnh)), N'') IS NULL THEN N'MISSING'
        WHEN CHARINDEX(N':', DuongDanAnh) > 0 OR LEFT(LTRIM(DuongDanAnh), 1) IN (N'/', N'\') THEN N'ROOTED_OR_ABSOLUTE'
        WHEN DuongDanAnh LIKE N'%..%' THEN N'PARENT_SEGMENT_RISK'
        ELSE N'RELATIVE_CANDIDATE'
    END AS PhotoPathClass,
    COUNT_BIG(*) AS VehicleRows
FROM dbo.XeTap
GROUP BY
    CASE
        WHEN NULLIF(LTRIM(RTRIM(DuongDanAnh)), N'') IS NULL THEN N'MISSING'
        WHEN CHARINDEX(N':', DuongDanAnh) > 0 OR LEFT(LTRIM(DuongDanAnh), 1) IN (N'/', N'\') THEN N'ROOTED_OR_ABSOLUTE'
        WHEN DuongDanAnh LIKE N'%..%' THEN N'PARENT_SEGMENT_RISK'
        ELSE N'RELATIVE_CANDIDATE'
    END;

SELECT @@TRANCOUNT AS SessionOpenTransactionCount;
GO
